### ISSUE TITLE
Installtion Packages Failed

### ISSUE THREAD

**Issue by b1narylife** [ethandunford/amazon_best_sellers#1]
Collecting pkg-resources==0.0.0

Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: )
No matching distribution found for pkg-resources==0.0.0

------------------------------

Getting the above error. After some reading it could be a proplem with Ubuntu & Metadata however I am unable to find a fix for this at the moment.

**Comment by ethandunford** [comment]
@damienksedgwick What were the steps to set up the project?


These were the steps I took.

```
python3 -m venv venv
source venv/bin/active
pip install -r requirements.txt
```
